### ISSUE TITLE
Move Readme usage clutter to project's wiki page

### ISSUE THREAD

**Issue by PROxZIMA** [PROxZIMA/DarkSpider#24]
[Usage](https://github.com/PROxZIMA/DarkSpider#usage) in README is still not detailed.
Based on current development as mentioned in #23 more functionality will  be included in future so it'll be better to move usage to Wiki pages.

**Comment by ApoorvaKashyap** [comment]
Just to clarify, you want to move the usage section of the readme to the wiki?

**Comment by PROxZIMA** [comment]
Yes, I have not yet figured out a proper layout to document the changes. Once that is done, we can start working on wiki

**Comment by ApoorvaKashyap** [comment]
Something like this, perhaps:

1. Getting Started 
    a. What is DarkSpider? 
    b. Installation Methods and Dependencies
2. Usage
    a. As extractor
    b. As crawler
    c. As Crawler + Extractor + Keyword Search
    d. Visualization of the Network Structure
3. How to Contribute?
    a. Forking and Creating PRs
    b. Testing
4. Changelogs

**Comment by ApoorvaKashyap** [comment]
I think that should cover the content distribution for now. More content can be added when the features are added,

**Comment by PROxZIMA** [comment]
Great, As of now that's a good start.

**Comment by PROxZIMA** [comment]
I just copied sections from readme to wiki pages. Earlier I thought it would a bit of hassle but it was pretty quick.
Thanks for your input @ApoorvaKashyap!!!
